name: "Build & Push NuGet"

on:
  release:
    types: [published]
jobs:
  deploy:
    name: "NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Get Release
      if: github.event_name == 'release'
      id: get-release
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install dependencies
      run: dotnet restore
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" PermissionExtensions/PermissionExtensions.csproj"  
    - name: Build
      run: dotnet build PermissionExtensions/PermissionExtensions.csproj --configuration Release --no-restore
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get-release.outputs.upload_url }}
        asset_path: PermissionExtensions/bin/Release/net461/PermissionExtensions.dll
        asset_name: PermissionExtensions.dll
        asset_content_type: application/x-msdownload
    - name: Push to NuGet
      run: dotnet nuget push PermissionExtensions/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
